const BUILDINGS = {
  "A1": { name: "본관", alias: "Administration" }, "A2": { name: "교양관", alias: "St. Thomas" }, "A3": { name: "종합민원센터", alias: "Service Center" },
  "A4": { name: "팔각정", alias: "Pavilion" }, "A6": { name: "제1학생회관", alias: "Student Union 1" }, "A7": { name: "제2학생회관", alias: "Cafeteria 1" },
  "A8": { name: "중앙도서관", alias: "Library" }, "A9": { name: "종합강의동", alias: "John Sye Hall" }, "A10": { name: "사육장", alias: "Animal House" },
  "A11": { name: "제2식당", alias: "Cafeteria 2" }, "A13": { name: "영선실", alias: "Carpenter Room" }, "B1": { name: "취창업관", alias: "Employment" },
  "B2": { name: "제르멩관", alias: "Germain Hall" }, "B3": { name: "성당(교목처)", alias: "Chapel" }, "B4": { name: "국제관", alias: "International Hall" },
  "B5": { name: "학생군사교육단", alias: "ROTC" }, "B6": { name: "박물관", alias: "Museum" }, "B7": { name: "강당", alias: "Auditorium" },
  "B8": { name: "산학협력관", alias: "John Choi Hall" }, "C1": { name: "성토마스모어관", alias: "More Hall" }, "C2": { name: "성라이문도관", alias: "Raymund Hall" },
  "C3": { name: "체육관", alias: "Gymnasium" }, "C4": { name: "성비토관", alias: "Vitus Hall" }, "C5": { name: "사제관", alias: "Rectory" },
  "C6": { name: "신학관", alias: "Seminary" }, "C7": { name: "성예로니모관", alias: "Jerome Hall" }, "C8": { name: "창고", alias: "Warehouse" },
  "C9": { name: "성요한보스코관", alias: "Bosco Hall" }, "C10": { name: "제3학생식당", alias: "Cafeteria 3" }, "C11": { name: "미래인재관", alias: "HRD Center" },
  "C12": { name: "성야고보관", alias: "James Hall" }, "C13": { name: "성마태오관", alias: "Matthew Hall" }, "D1": { name: "창업보육센터", alias: "Incubator" },
  "D2": { name: "공학관,제2산학협력관", alias: "Matthias Hall" }, "D3": { name: "해양바이오산업연구센터", alias: "Marine Bio" }, "D4": { name: "중앙기기센터", alias: "Research Fac." },
  "D5": { name: "성도미니코관", alias: "Dominic Hall" }, "D6": { name: "성이시도르관", alias: "Isidore Hall" }, "D7": { name: "제1약학관", alias: "Damiano Hall" },
  "D8": { name: "정보통신관", alias: "IT Center" }, "D9": { name: "성토마스관", alias: "Thomas Hall" }, "D10": { name: "제2약학관", alias: "Cosmas Hall" },
  "D11": { name: "성마르타관", alias: "Martha Hall" }, "D12": { name: "미술실습동", alias: "Fine Arts Lab" }, "D15": { name: "성카타리나관", alias: "Catherine Hall" },
  "D16": { name: "아마레갤러리", alias: "Cafeteria 4" }, "D17": { name: "성체칠리아관", alias: "Cecilia Hall" }, "D18": { name: "성안나관", alias: "Anna Hall" },
  "E1": { name: "성바오로문화관", alias: "Paul Hall" }, "E3": { name: "기숙사 아마레관", alias: "Amare Hall" }, "E4": { name: "기숙사 행정동", alias: "Dormitory Admin" },
  "E5": { name: "기숙사 예지관", alias: "Wisdom Hall" }, "E6": { name: "기숙사 세르비레관", alias: "Servire Hall" }, "E7": { name: "기숙사 효성관", alias: "Morning Star Hall" },
  "E8": { name: "기숙사 성김대건관", alias: "Andrew Hall" }, "E9": { name: "기숙사 다솜관", alias: "Charity Hall" }, "E10": { name: "기숙사 참인재관", alias: "HCC Hall" },
  "E11": { name: "성이윤일관", alias: "Admissions" }, "E12": { name: "대가빌라1동", alias: "Christopher's House" }, "E13": { name: "대가빌라2동", alias: "Clarion House" }
};

const SAMPLE_FACILITIES = [
  {id:"f5", buildingCode:"E4", category:"식당", name:"소담한식", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"19:00"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"f6", buildingCode:"E4", category:"식당", name:"한솥도시락", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:30"}]},
  {id:"f7", buildingCode:"E4", category:"식당", name:"맘스터치", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"21:00"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"f8", buildingCode:"E4", category:"식당", name:"매울양양", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:30",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"fa", buildingCode:"E4", category:"식당", name:"델리지오소", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"13:30"}]},
  {id:"fb", buildingCode:"E4", category:"식당", name:"낭만테라스", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"14:30"}]},
  {id:"fc_1", buildingCode:"E4", category:"식당", name:"홍대불고기", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"fc_2", buildingCode:"E4", category:"식당", name:"홍대함바그", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"fd_1", buildingCode:"E4", category:"식당", name:"홍대보쌈", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"fd_2", buildingCode:"E4", category:"식당", name:"카츠3.9", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:30"},{period:"학기중",dayType:"주말",open:"11:00",close:"19:00"}]},
  {id:"f13", buildingCode:"E4", category:"편의점", name:"GS25", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"07:30",close:"25:00"},{period:"학기중",dayType:"주말",open:"09:00",close:"25:00"}]},
  {id:"f19", buildingCode:"E4", category:"카페", name:"마시그레이", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"21:00"},{period:"학기중",dayType:"주말",open:"12:00",close:"18:00"}]},
  {id:"f1", buildingCode:"A7", category:"식당", name:"제1학생식당", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"11:00",close:"17:30"}]},
  {id:"f2", buildingCode:"C10", category:"식당", name:"제3학생식당", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"17:00"}]},
  {id:"f3", buildingCode:"D16", category:"식당", name:"제4학생식당(식당)", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"11:00",close:"14:30"}]},
  {id:"f4", buildingCode:"D16", category:"카페", name:"제4학생식당(카페)", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"15:30"}]},
  {id:"f9", buildingCode:"B2", category:"식당", name:"교직원식당", floor:"1F", schedules:[{period:"연중",dayType:"평일",open:"11:30",close:"13:30"}]},
  {id:"f10", buildingCode:"A2", category:"편의점", name:"CU", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"07:30",close:"20:30"}]},
  {id:"f11", buildingCode:"A6", category:"편의점", name:"세븐일레븐", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"19:00"}]},
  {id:"f12", buildingCode:"B8", category:"편의점", name:"착한편의점", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"19:00"}]},
  {id:"f14", buildingCode:"A8", category:"카페", name:"블루포트 중앙도서관점", floor:"B1", schedules:[{period:"학기중",dayType:"평일",open:"08:30",close:"19:00"}]},
  {id:"f15", buildingCode:"A9", category:"카페", name:"그라찌에", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:30",close:"18:00"}]},
  {id:"f16", buildingCode:"B1", category:"카페", name:"블루포트 취창업관점", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"18:00"},{period:"학기중",dayType:"주말",open:"09:00",close:"15:00"}]},
  {id:"f17", buildingCode:"C7", category:"카페", name:"카페ing", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"18:00"},{period:"학기중",dayType:"토",open:"10:00",close:"17:00"}]},
  {id:"f18", buildingCode:"A6", category:"카페", name:"허브에스", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"19:00"}]},
  {id:"f20", buildingCode:"A2", category:"복지", name:"우편취급국", floor:"1F", schedules:[{period:"연중",dayType:"평일",open:"09:00",close:"18:00"}]},
  {id:"f21", buildingCode:"A3", category:"복지", name:"구내서점", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"17:00"}]},
  {id:"f22", buildingCode:"A6", category:"복지", name:"출력센터(복사실)", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"17:00"}]},
  {id:"f23", buildingCode:"A2", category:"복지", name:"우리문구", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:30",close:"17:30"}]},
  {id:"f24", buildingCode:"A6", category:"복지", name:"구내사진관", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"18:00"}]},
  {id:"f26", buildingCode:"A2", category:"복지", name:"보건진료소", floor:"1F", schedules:[{period:"연중",dayType:"평일",open:"09:00",close:"17:00"}]},
  {id:"f27", buildingCode:"B6", category:"문화", name:"박물관", floor:"1F", schedules:[{period:"연중",dayType:"평일",open:"09:30",close:"16:30"}]},
  {id:"lib_dmz", buildingCode:"A8", category:"학습", name:"Digital Maker Zone", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"21:00"}]},
  {id:"lib_commons", buildingCode:"A8", category:"학습", name:"창의융합러닝커먼스", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"21:00"}]},
  {id:"lib_lounge", buildingCode:"A8", category:"학습", name:"D-Study Lounge", floor:"1F", schedules:[{period:"학기중",dayType:"평일",open:"07:00",close:"24:00"},{period:"학기중",dayType:"주말",open:"07:00",close:"24:00"}]},
  {id:"lib_2f", buildingCode:"A8", category:"학습", name:"자연/기술과학실", floor:"2F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"21:00"}]},
  {id:"lib_3f", buildingCode:"A8", category:"학습", name:"예술/어문학실", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"21:00"}]},
  {id:"lib_4f", buildingCode:"A8", category:"학습", name:"인문/사회과학실", floor:"4F", schedules:[{period:"학기중",dayType:"평일",open:"09:00",close:"21:00"}]},
  {id:"lib_5f", buildingCode:"A8", category:"학습", name:"열람실", floor:"5F", schedules:[{period:"학기중",dayType:"평일",open:"07:00",close:"24:00"},{period:"학기중",dayType:"주말",open:"07:00",close:"24:00"}]},
  {id:"gym_3f", buildingCode:"E1", category:"복지", name:"헬스장", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"07:00",close:"21:00"},{period:"방학중",dayType:"평일",open:"09:00",close:"17:00"},{period:"연중",dayType:"공휴일",closed:true}]},
  {id:"gym_test", buildingCode:"E1", category:"복지", name:"체력측정존", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:00"},{period:"방학중",dayType:"평일",open:"10:00",close:"16:00"}]},
  {id:"gym_prog", buildingCode:"E1", category:"복지", name:"프로그램실", floor:"2F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"20:00"},{period:"방학중",dayType:"평일",open:"09:00",close:"17:00"}]},
  {id:"gym_fit", buildingCode:"E1", category:"복지", name:"피팅룸", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"07:00",close:"21:00"}]},
  {id:"gym_shower", buildingCode:"E1", category:"복지", name:"탈의실 및 샤워실", floor:"2F", schedules:[{period:"학기중",dayType:"평일",open:"08:00",close:"21:00"},{period:"방학중",dayType:"평일",open:"10:00",close:"17:00"}]},
  {id:"gym_locker", buildingCode:"E1", category:"복지", name:"탈의실", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"07:00",close:"21:00"}]},
  {id:"gym_cons", buildingCode:"E1", category:"복지", name:"운동처방실(304호)", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"17:00",close:"20:00"},{period:"방학중",dayType:"평일",open:"09:00",close:"17:00"}]},
  {id:"gym_off", buildingCode:"E1", category:"복지", name:"사무실(310호)", floor:"3F", schedules:[{period:"학기중",dayType:"평일",open:"10:00",close:"16:30"}]}
];